#!/usr/bin/env bash
# Write the ConfigMaps db-init and keycloak-realm of the config repository from db/ and keycloak/; --check only fails when the committed copies differ from them.
# Plumbing, not a lesson: the config repository holds only manifests, so the files scripts/k8s/deploy.sh turned into ConfigMaps are committed there as ConfigMaps.
set -euo pipefail
cd "$(dirname "$0")/../.."

render() {
  echo "# Generated by scripts/devops/gitops-render.sh from $2; do not edit by hand."
  shift 2
  kubectl create configmap "$@" -n donhang --dry-run=client -o yaml
}

status=0
for env in staging production; do
  dir=deploy/gitops/config-repo/envs/$env
  new_db=$(render db-init "db/schema.sql, db/seed.sql and db/migrations-baseline.sql" db-init \
    --from-file=10-schema.sql=db/schema.sql \
    --from-file=20-seed.sql=db/seed.sql \
    --from-file=30-migrations-baseline.sql=db/migrations-baseline.sql)
  new_realm=$(render keycloak-realm "keycloak/donhang-realm.json" keycloak-realm \
    --from-file=donhang-realm.json=keycloak/donhang-realm.json)
  if [ "${1:-}" = --check ]; then
    for pair in "db-init:$new_db" "keycloak-realm:$new_realm"; do
      name=${pair%%:*}
      if [ "${pair#*:}" != "$(cat "$dir/$name.yaml")" ]; then
        echo "$dir/$name.yaml differs from what scripts/devops/gitops-render.sh writes" >&2
        status=1
      fi
    done
  else
    printf '%s\n' "$new_db" > "$dir/db-init.yaml"
    printf '%s\n' "$new_realm" > "$dir/keycloak-realm.yaml"
    echo "wrote $dir/db-init.yaml and $dir/keycloak-realm.yaml"
  fi
done
exit "$status"
