-- The whole Đơn Hàng database at stage-0. Money is stored in whole đồng, so
-- every amount is an integer. Times are stored with a time zone, always.

CREATE TABLE products (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      text NOT NULL,
    price_vnd integer NOT NULL CHECK (price_vnd > 0)
);

-- lesson: foundation.l1.tables-keys-relations
CREATE TABLE customers (
    id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email     text NOT NULL UNIQUE,
    city      text NOT NULL
);

CREATE TABLE orders (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id integer NOT NULL REFERENCES customers (id),
    placed_at   timestamptz NOT NULL,
    status      text NOT NULL
                CHECK (status IN ('new', 'paid', 'shipped', 'cancelled'))
);

CREATE TABLE order_items (
    order_id       integer NOT NULL REFERENCES orders (id),
    product_id     integer NOT NULL REFERENCES products (id),
    quantity       integer NOT NULL CHECK (quantity > 0),
    unit_price_vnd integer NOT NULL CHECK (unit_price_vnd > 0),
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE payments (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   integer NOT NULL REFERENCES orders (id),
    paid_at    timestamptz NOT NULL,
    amount_vnd integer NOT NULL CHECK (amount_vnd > 0),
    method     text NOT NULL CHECK (method IN ('card', 'bank_transfer', 'cod'))
);

CREATE TABLE notifications (
    id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL REFERENCES orders (id),
    channel  text NOT NULL CHECK (channel IN ('email', 'sms')),
    sent_at  timestamptz NOT NULL,
    subject  text NOT NULL
);
